//
// Created by Marvel  Asuenimhen  on 06/04/25.
//

#ifndef SEMAPHORE_KEYS_H
#define SEMAPHORE_KEYS_H


#define SEM_KEY_BASE 9000 // semaphore base key

#define DIRETTORE_SEMAPHORE_KEY 100
#define OPERATORE_SEMAPHORE_KEY 200
#define SPORTELLO_SEMAPHORE_KEY 300
#define QUEUE_SEMAPHORE_KEY 400
#define SIM_TIME_SEMAPHORE_KEY 500
#define STATISTIC_SEMAPHORE_KEY 900
#define TICKET_EROGATOR_SEMAPHORE_KEY 700

#endif //SEMAPHORE_KEYS_H
